-- Generated by `drizzle-kit generate`, then HAND-EDITED in two places. Both
-- edits are deliberate and load-bearing; do not "tidy" them back to drizzle's
-- output. They are invisible to `drizzle-kit`, which models neither `IF NOT
-- EXISTS` nor constraint validity, so meta/0015_snapshot.json matches
-- lib/db/schema.ts exactly and a future `generate` produces no spurious diff.
--
--   1. `IF NOT EXISTS` on the CREATE statements. Migrations here are applied
--      BY HAND (`npm run db:migrate`) and nothing in CI applies them — the
--      2026-09-03 incident behind scripts/check-schema-drift.ts. Re-running a
--      file whose journal entry did not land must be a no-op, not an error.
--   2. `NOT VALID` on the CHECK constraint. See the block below.
CREATE TABLE IF NOT EXISTS "intake_attempts" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"surface" text NOT NULL,
	"submitter_ip_hash" text NOT NULL
);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "intake_attempts_surface_ip_created_idx" ON "intake_attempts" USING btree ("surface","submitter_ip_hash","created_at");--> statement-breakpoint
-- `NOT VALID` — required, not cautious. An ordinary ADD CONSTRAINT scans the
-- whole table and ABORTS THE WHOLE MIGRATION if a single existing row fails
-- it, and `submissions.status` has been plain `text` with only a DEFAULT since
-- 0001: nothing in the schema proves what the ~production queue actually
-- contains (a typo'd 'Approved', a legacy value, an ad-hoc Neon UPDATE). This
-- migration is applied by hand against the live Neon database, so a failure
-- here is an outage, and the fix would then have to be found under time
-- pressure with the migration half-applied.
--
-- `NOT VALID` skips validating PRE-EXISTING rows ONLY. It fully enforces the
-- constraint on every INSERT and UPDATE from the moment it lands, which is the
-- entire point of this change: a future writer that explicitly passes
-- `status: 'approved'` is rejected by Postgres. It deliberately does NOT
-- retroactively judge rows a human already reviewed.
--
-- FOLLOW-UP, once the live queue has been checked:
--     SELECT DISTINCT status FROM submissions;   -- expect only the three below
--     ALTER TABLE "submissions" VALIDATE CONSTRAINT "submissions_status_check";
-- VALIDATE takes only a SHARE UPDATE EXCLUSIVE lock (concurrent reads and
-- writes continue) and is safe to run any time. Until it runs, the guarantee
-- is "no new bad row," not "no bad row" — untracked by any test, because
-- nothing can test the contents of a database this suite cannot reach.
ALTER TABLE "submissions" ADD CONSTRAINT "submissions_status_check" CHECK ("submissions"."status" IN ('pending', 'approved', 'rejected')) NOT VALID;
