import { describe, it, expect } from "vitest";
import { render, screen } from "@testing-library/react";

import { PlateKey } from "./plate-key";

// ---------------------------------------------------------------------------
// Fixtures
// ---------------------------------------------------------------------------

// Props are passed EXPLICITLY rather than imported from
// components/home/hero-plate-paths: that artifact is regenerated by every data
// wave, so asserting against its live numbers here would make this file's
// expectations drift silently. The value happens to match the current
// snapshot; nothing depends on it continuing to.
const BASE_PROPS = {
  plotted: 1920,
};

const ALL_STATUS_LABELS = [
  "Operational",
  "Under construction",
  "Permitted",
  "Proposed",
  "Cancelled",
];

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

describe("PlateKey legend", () => {
  // The reason this component exists: the plate encodes status in colour
  // alone. Each entry pairs the label with an aria-hidden icon in the status
  // colour, so status reads by shape and text as well as hue.
  it.each(ALL_STATUS_LABELS)("names the %s status", (label) => {
    render(<PlateKey {...BASE_PROPS} />);
    expect(screen.getByText(label)).toBeInTheDocument();
  });

  it("lists every status exactly once", () => {
    render(<PlateKey {...BASE_PROPS} />);
    for (const label of ALL_STATUS_LABELS) {
      expect(screen.getAllByText(label)).toHaveLength(1);
    }
  });

  // Marks are not facilities — co-located same-status sites collapse onto one
  // mark — so the legend deliberately carries no per-status numbers. A future
  // edit that "helpfully" adds HERO_PLATE.counts here would be captioning
  // drawn marks as facility counts, which the artifact's doc comment forbids.
  it("renders no per-status counts", () => {
    const { container } = render(<PlateKey {...BASE_PROPS} />);
    const legend = container.querySelector("ul");
    expect(legend).not.toBeNull();
    expect(legend?.textContent).not.toMatch(/\d/);
  });
});

describe("PlateKey caption", () => {
  it("states how many sites the plate draws ground for, with separators", () => {
    render(<PlateKey {...BASE_PROPS} />);
    expect(screen.getByText("1,920 sites plotted")).toBeInTheDocument();
  });

  // ---- the invariant this component was stripped to protect ----

  // ONE number. The caption used to read "1,920 of 1,929 sites plotted", whose
  // second total came from the build-time plate artifact while
  // <HeroProvenance>'s `sites` a few lines above comes from live Neon — equal
  // today, contradictory the first data sync that lands without a plate
  // rebuild. Anchored at BOTH ends on purpose: an unanchored match passes
  // happily against "1,920 sites plotted · <anything>", which is precisely the
  // regression. Restoring the old caption, appending an omission segment, or
  // adding any further clause all fail here.
  it("states exactly one number, with nothing appended", () => {
    render(<PlateKey {...BASE_PROPS} />);

    const caption = screen.getByText(/sites plotted/);
    expect(caption.textContent).toMatch(/^1,920 sites plotted$/);

    // Belt and braces on the number itself: one digit-group run in the whole
    // caption. A second total added as a bare number rather than after a
    // separator already fails the anchored match above — this asserts the same
    // thing from the other side, so the guarantee does not rest on one regex,
    // and it catches a second number introduced anywhere in the caption's text
    // node.
    expect(caption.textContent?.match(/[\d,]+/g)).toHaveLength(1);
  });

  it("formats the count with thousands separators", () => {
    render(<PlateKey plotted={1929} />);
    expect(screen.getByText("1,929 sites plotted")).toBeInTheDocument();
  });

  // The four territory NAMES were cut from this caption (Ed, 2026-09-15). The
  // disclosure itself was not: <HeroProvenance> renders "static map omits N in
  // U.S. territories" at every viewport and every mount state, which is the
  // durable version of it. This asserts the names stay out of the KEY — it is
  // deliberately not a statement about the disclosure, which lives in
  // components/home/hero-provenance.test.tsx and must keep passing.
  it("carries no territory prose", () => {
    const { container } = render(<PlateKey {...BASE_PROPS} />);
    expect(container.textContent).not.toMatch(/Albers/);
    expect(container.textContent).not.toMatch(/cannot place/);
    expect(container.textContent).not.toMatch(/Puerto Rico|Guam/);
  });
});

describe("PlateKey chrome", () => {
  // The map link ("Open the interactive map →") was removed as a duplicate of
  // the hero's primary "Explore the map" CTA a few lines above. The card now
  // holds nothing focusable, so it adds no tab stop between that CTA row and
  // what follows. A link added back here would also reintroduce the Playwright
  // strict-mode hazard the old name was carefully steered around.
  it("holds no links", () => {
    render(<PlateKey {...BASE_PROPS} />);
    expect(screen.queryAllByRole("link")).toHaveLength(0);
  });
});
