import { getStatusMeta } from "@/lib/status";
import { getFacilityTypeMeta } from "@/lib/facility-type";
import type { Facility } from "@/lib/schema";

/**
 * Initial view centered on the contiguous United States.
 * Zoom 3.4 shows all 48 contiguous states comfortably.
 */
export const INITIAL_VIEW_STATE = {
  longitude: -98.5,
  latitude: 39.5,
  zoom: 3.4,
} as const;

/**
 * Custom "flat parchment atlas" basemap style — generated by
 * `scripts/build-parchment-style.mjs` from OpenFreeMap's positron style
 * over the same OpenFreeMap openmaptiles vector tiles.
 *
 * Warm parchment land (#F5F1E6), pale slate-blue water (#C9D6DA), ink
 * hairline roads/boundaries, muted-ink labels with parchment halos, faint
 * green parks. No hillshade. Committed as a pinned snapshot; regenerate with
 * `npm run build:basemap`.
 */
export const BASEMAP_STYLE_URL = "/basemap/parchment.json";

/**
 * Esri World Imagery — keyless raster satellite basemap for the map's
 * streets↔satellite toggle. Sub-meter imagery in most US areas down to ~z19.
 * Tile path is /tile/{z}/{y}/{x} (level/row/col), which maps directly to
 * MapLibre's {z}/{y}/{x} raster template. No API key; attribution required
 * by Esri's ToS. The legacy services.arcgisonline.com endpoint is the
 * community-standard keyless access path.
 */
export const SATELLITE_TILE_URL =
  "https://services.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}";

/** Live MapServer copyrightText (Maxar rebranded to Vantor in 2025). */
export const SATELLITE_ATTRIBUTION = "Esri, Vantor, Earthstar Geographics";

/** Cap native tile requests at z19 (sub-meter ceiling); MapLibre oversamples above, avoiding z20+ 404 gaps in rural areas. */
export const SATELLITE_MAX_ZOOM = 19;

/**
 * Builds a descriptive accessible label for a facility map marker.
 * Format: "Name, Operator — City, ST — Type — Status — N MW [operational|planned]"
 * Capacity segment is omitted when capacityMw is not present.
 *
 * @example
 * buildMarkerLabel(colossus)
 * // "Colossus, xAI — Memphis, TN — Data center — Operational — 150 MW operational"
 */
export function buildMarkerLabel(f: Facility): string {
  const meta = getStatusMeta(f.status);
  const typeLabel = getFacilityTypeMeta(f.facilityType).label;
  const cityState = f.location.city
    ? `${f.location.city}, ${f.location.state}`
    : f.location.state;

  const parts: string[] = [
    `${f.name}, ${f.operator}`,
    cityState,
    typeLabel,
    meta.label,
  ];

  if (f.capacityMw?.operational !== undefined) {
    parts.push(`${f.capacityMw.operational} MW operational`);
  } else if (f.capacityMw?.planned !== undefined) {
    parts.push(`${f.capacityMw.planned} MW planned`);
  }

  return parts.join(" — ");
}
