import { getStatusMeta } from "@/lib/status";
import { getFacilityTypeMeta } from "@/lib/facility-type";
import type { Facility } from "@/lib/schema";

/**
 * Initial view centered on the contiguous United States.
 * Zoom 3.4 shows all 48 contiguous states comfortably.
 */
export const INITIAL_VIEW_STATE = {
  longitude: -98.5,
  latitude: 39.5,
  zoom: 3.4,
} as const;

/**
 * Custom "flat parchment atlas" basemap style — generated by
 * `scripts/build-parchment-style.mjs` from OpenFreeMap's positron style
 * over the same OpenFreeMap openmaptiles vector tiles.
 *
 * Warm parchment land (#F5F1E6), pale slate-blue water (#C9D6DA), ink
 * hairline roads/boundaries, muted-ink labels with parchment halos, faint
 * green parks. No hillshade. Committed as a pinned snapshot; regenerate with
 * `npm run build:basemap`.
 */
export const BASEMAP_STYLE_URL = "/basemap/parchment.json";

/**
 * Esri World Imagery — keyless raster satellite basemap for the map's
 * streets↔satellite toggle. Sub-meter imagery in most US areas down to ~z19.
 * Tile path is /tile/{z}/{y}/{x} (level/row/col), which maps directly to
 * MapLibre's {z}/{y}/{x} raster template. No API key; attribution required
 * by Esri's ToS. The legacy services.arcgisonline.com endpoint is the
 * community-standard keyless access path.
 */
export const SATELLITE_TILE_URL =
  "https://services.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}";

/** Live MapServer copyrightText (Maxar rebranded to Vantor in 2025). */
export const SATELLITE_ATTRIBUTION = "Esri, Vantor, Earthstar Geographics";

/** Cap native tile requests at z19 (sub-meter ceiling); MapLibre oversamples above, avoiding z20+ 404 gaps in rural areas. */
export const SATELLITE_MAX_ZOOM = 19;

/**
 * Builds a descriptive accessible label for a facility map marker.
 * Format: "Name, Operator — City, ST — Type — Status — N MW [operational|planned]"
 * Capacity segment is omitted when capacityMw is not present.
 *
 * @example
 * buildMarkerLabel(colossus)
 * // "Colossus, xAI — Memphis, TN — Data center — Operational — 150 MW operational"
 */
export function buildMarkerLabel(f: Facility): string {
  const meta = getStatusMeta(f.status);
  const typeLabel = getFacilityTypeMeta(f.facilityType).label;
  const cityState = f.location.city
    ? `${f.location.city}, ${f.location.state}`
    : f.location.state;

  const parts: string[] = [
    `${f.name}, ${f.operator}`,
    cityState,
    typeLabel,
    meta.label,
  ];

  if (f.capacityMw?.operational !== undefined) {
    parts.push(`${f.capacityMw.operational} MW operational`);
  } else if (f.capacityMw?.planned !== undefined) {
    parts.push(`${f.capacityMw.planned} MW planned`);
  }

  return parts.join(" — ");
}

/** Geographic bounding box computed from a set of facilities, for camera framing. */
export interface FacilitiesBounds {
  bounds: [[number, number], [number, number]]; // [[minLon,minLat],[maxLon,maxLat]]
  center: [number, number]; // [lon, lat]
  isCoincident: boolean;
}

/**
 * Computes the geographic bounding box of a set of facilities for camera framing.
 * Returns null for an empty set. `isCoincident` is true when all facilities are
 * essentially co-located (bbox smaller than ~0.001°), so callers can center+zoom
 * instead of fitting a degenerate box.
 */
export function computeFacilitiesBounds(
  facilities: Facility[]
): FacilitiesBounds | null {
  if (facilities.length === 0) return null;

  const lons = facilities.map((f) => f.location.lon);
  const lats = facilities.map((f) => f.location.lat);
  const minLon = Math.min(...lons);
  const maxLon = Math.max(...lons);
  const minLat = Math.min(...lats);
  const maxLat = Math.max(...lats);
  const isCoincident = maxLon - minLon < 0.001 && maxLat - minLat < 0.001;

  return {
    bounds: [
      [minLon, minLat],
      [maxLon, maxLat],
    ],
    center: [(minLon + maxLon) / 2, (minLat + maxLat) / 2],
    isCoincident,
  };
}

/** Padded, aspect-corrected geographic frame for the locator inset's mini-map. */
export interface LocatorFrame {
  minLon: number;
  maxLon: number;
  minLat: number;
  maxLat: number;
  width: number;
  height: number;
}

/** Guards a degenerate (zero-span) bbox from producing an infinite/NaN aspect ratio. */
const MIN_SPAN_DEGREES = 0.5;

/** Locator inset SVG width is clamped to this pixel range regardless of aspect ratio. */
const LOCATOR_WIDTH_RANGE: [number, number] = [90, 160];

/**
 * Computes a padded, aspect-corrected geographic frame for the locator inset —
 * the small overview map that plots the full facility footprint as ink dots.
 * Returns null when there are no facilities to frame.
 *
 * The bbox is padded outward by `pad` (a fraction of each axis's span) so dots
 * never touch the frame edge. Longitude span is corrected for latitude
 * (a degree of longitude shrinks by cos(latitude) toward the poles) so the
 * resulting width/height aspect ratio isn't visually stretched.
 */
export function computeLocatorFrame(
  facilities: Facility[],
  height = 76,
  pad = 0.06
): LocatorFrame | null {
  const bounds = computeFacilitiesBounds(facilities);
  if (!bounds) return null;

  const [[rawMinLon, rawMinLat], [rawMaxLon, rawMaxLat]] = bounds.bounds;

  const lonSpan = Math.max(rawMaxLon - rawMinLon, MIN_SPAN_DEGREES);
  const latSpan = Math.max(rawMaxLat - rawMinLat, MIN_SPAN_DEGREES);

  const lonPad = lonSpan * pad;
  const latPad = latSpan * pad;

  const minLon = rawMinLon - lonPad;
  const maxLon = rawMaxLon + lonPad;
  const minLat = rawMinLat - latPad;
  const maxLat = rawMaxLat + latPad;

  const midLat = (minLat + maxLat) / 2;
  const effectiveLonSpan =
    (maxLon - minLon) * Math.cos((midLat * Math.PI) / 180);
  const paddedLatSpan = maxLat - minLat;

  const rawWidth = height * (effectiveLonSpan / paddedLatSpan);
  const width = Math.round(
    Math.min(Math.max(rawWidth, LOCATOR_WIDTH_RANGE[0]), LOCATOR_WIDTH_RANGE[1])
  );

  return { minLon, maxLon, minLat, maxLat, width, height };
}

/**
 * Projects a geographic coordinate into the locator inset's SVG pixel space
 * defined by `frame`. Y is inverted (north → y0) to match SVG's top-down
 * coordinate system. Does not clamp — callers that need a clamped viewport
 * rectangle (e.g. panning outside the frame) clamp themselves.
 */
export function projectToFrame(
  lon: number,
  lat: number,
  frame: LocatorFrame
): { x: number; y: number } {
  const { minLon, maxLon, minLat, maxLat, width, height } = frame;
  const x = ((lon - minLon) / (maxLon - minLon)) * width;
  const y = ((maxLat - lat) / (maxLat - minLat)) * height;
  return { x, y };
}
